# Generated by Django 4.1.1 on 2022-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='scanned_nrc',
        ),
        migrations.AddField(
            model_name='admission',
            name='scanned_nrc_back',
            field=models.FileField(blank=True, null=True, upload_to="id/nrc/%Y/%m/%d'"),
        ),
        migrations.AddField(
            model_name='admission',
            name='scanned_nrc_front',
            field=models.FileField(blank=True, null=True, upload_to="id/nrc/%Y/%m/%d'"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='application_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], default='Pending Review', max_length=200, verbose_name='Application Status'),
        ),
    ]
