# Generated by Django 4.1.1 on 2023-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application_stage',
            field=models.CharField(choices=[('Admissions Office', 'Admissions Office'), ('Accounts Office', 'Accounts Office'), ('Dean Of Students Affairs Office', 'Dean Of Students Affairs Office'), ('ICT Office', 'ICT Office'), ('Program Coordinator or Principal Lecturer Office', 'Program Coordinator or Principal Lecturer Office'), ('Registrar Office', 'Registrar Office'), ('Lecturer', 'Lecturer'), ('Other', 'Other')], default='Admissions Office', max_length=200, verbose_name='Application Stage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(blank=True, choices=[('Admissions Office', 'Admissions Office'), ('Accounts Office', 'Accounts Office'), ('Dean Of Students Affairs Office', 'Dean Of Students Affairs Office'), ('ICT Office', 'ICT Office'), ('Program Coordinator or Principal Lecturer Office', 'Program Coordinator or Principal Lecturer Office'), ('Registrar Office', 'Registrar Office'), ('Lecturer', 'Lecturer'), ('Other', 'Other')], max_length=60, null=True, verbose_name='User Group'),
        ),
    ]
