# Generated by Django 4.1.1 on 2022-12-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_remove_admission_scanned_nrc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='subject_biology_human_and_social',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Biology/Human & Social'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_english',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_mathematics',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mathematics'),
        ),
    ]
