# Generated by Django 4.1.1 on 2023-01-25 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Admission Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.admission'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
    ]
