# Generated by Django 4.1.1 on 2023-01-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_admission_application_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student_number',
            field=models.ForeignKey(default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='full_student_number', to='schoolapp.studentnumber', verbose_name='Student Number'),
        ),
    ]
