# Generated by Django 4.1.1 on 2023-02-02 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_student_admission_date_remove_student_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_details',
        ),
        migrations.AddField(
            model_name='student',
            name='student_admission_details',
            field=models.ForeignKey(blank=True, help_text='search by student number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.admission'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2005, 1, 1, 0, 0), max_length=200, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='intake',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schoolapp.session', verbose_name='In-take'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='search by student number', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
