# Generated by Django 4.1.1 on 2022-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_admission_subject_biology_human_and_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='subject_chemistry',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Chemistry'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_civic_education',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Civic Education'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_commerce',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Commerce'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_geography',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Geography'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_history',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_home_economics',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Home Economics'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_physical_science',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Physical Science'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_physics',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Physics'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject_religious_education',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Religious Education'),
        ),
    ]
