# Generated by Django 4.1.1 on 2023-01-15 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_admission_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(default='', max_length=500, verbose_name='Name Of School')),
                ('address', models.CharField(blank=True, default='School Address', max_length=200, null=True, verbose_name='School Address')),
                ('email', models.CharField(blank=True, default='exampleemail@exampleemail.com', max_length=200, null=True, verbose_name='Email Address')),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Facebook Page Link')),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Instagram')),
                ('phone', models.CharField(blank=True, default='Tel/Cell Number', max_length=200, null=True, verbose_name='Tel/Cell')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='school/logo/%Y/%m/%d', verbose_name='School logo')),
            ],
            options={
                'verbose_name': 'School Details',
                'verbose_name_plural': 'School Details',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to="users/pictures/%Y/%m/%d'"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='application_stage',
            field=models.CharField(choices=[('Admissions Office', 'Admissions Office'), ('Accounts Office', 'Accounts Office'), ('Dean Of Students Affairs Office', 'Dean Of Students Affairs Office'), ('ICT Office', 'ICT Office'), ('Program Coordinator or Principal Lecturer Office', 'Program Coordinator or Principal Lecturer Office'), ('Registrar Office', 'Registrar Office'), ('Lecturer', 'Lecturer'), ('Other Staff', 'Other Staff')], default='Admissions Office', max_length=200, verbose_name='Application Stage'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(blank=True, choices=[('Admissions Office', 'Admissions Office'), ('Accounts Office', 'Accounts Office'), ('Dean Of Students Affairs Office', 'Dean Of Students Affairs Office'), ('ICT Office', 'ICT Office'), ('Program Coordinator or Principal Lecturer Office', 'Program Coordinator or Principal Lecturer Office'), ('Registrar Office', 'Registrar Office'), ('Lecturer', 'Lecturer'), ('Other Staff', 'Other Staff')], max_length=60, null=True, verbose_name='User Group'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=20, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('venue', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='Venue')),
                ('description', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('exam', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('comment', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_courses', to='schoolapp.course')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(default='', help_text='name of class, (eg. A)', max_length=200, verbose_name='Enter Class Title')),
                ('courses', models.ManyToManyField(help_text='Hold Ctrl to choose multiple', related_name='class_subject', to='schoolapp.course', verbose_name='Choose Courses')),
                ('grade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.level', verbose_name='Level')),
                ('lecturer', models.ForeignKey(default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assign Lecturer')),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.FloatField(null=True)),
                ('cgpa', models.FloatField(null=True)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=100)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.level', verbose_name='Level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='PupilAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=50)),
                ('daysdate', models.DateField(default='', verbose_name='Attended On')),
                ('nameofclass', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schoolclass', verbose_name='Class')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance',
            },
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentOfTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(default='', max_length=200, verbose_name='Lecturer')),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.department', verbose_name='Name Of Department')),
            ],
            options={
                'verbose_name': 'Lecturer And Department',
                'verbose_name_plural': 'Lecturer And Department',
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='allocated_course', to='schoolapp.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField(max_length=10000, verbose_name='News Details')),
                ('announcementdatetime', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('teacher', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lecturers Name')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
