# Generated by Django 4.1.1 on 2023-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_admission_subject_chemistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='application_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=200, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='marital_status',
            field=models.CharField(choices=[('---------', '---------'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], default='Single', max_length=200, verbose_name='Marital Status'),
        ),
    ]
