# Generated by Django 4.1.1 on 2023-01-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_schooldetails_user_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.ForeignKey(default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.studentnumber', verbose_name='Student Number'),
        ),
    ]
