# Generated by Django 4.1.1 on 2023-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_admission_application_date_alter_admission_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application_status',
            field=models.CharField(blank=True, choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Review', max_length=200, null=True, verbose_name='Application Status'),
        ),
    ]
