# Generated by Django 4.1.1 on 2023-01-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_alter_student_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Category')),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount To Be Paid')),
                ('description', models.ForeignKey(default='', help_text='payment for?', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.paymentcategory', verbose_name='Payment Category')),
                ('payment_level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.level', verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Payment Structure',
                'verbose_name_plural': 'Payment Structure',
            },
        ),
    ]
