# Generated by Django 4.1.1 on 2023-01-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_alter_admission_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='DOB'),
        ),
    ]
