# Generated by Django 4.1.1 on 2023-01-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_paymentcategory_paymentstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountpaid', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount Paid')),
                ('actualamountpaid', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Actual Amount Paid')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Balance')),
                ('paymentstatus', models.CharField(blank=True, default='Fully Paid', editable=False, max_length=30, null=True)),
                ('paymentdate', models.DateField(auto_now=True, verbose_name='Payment Date')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Amount To Be Paid')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Type')),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Type',
            },
        ),
        migrations.RenameField(
            model_name='paymentstructure',
            old_name='amount',
            new_name='amount_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='paymentstructure',
            name='description',
        ),
        migrations.DeleteModel(
            name='PaymentCategory',
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentstructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.paymentstructure', verbose_name='Choose Payment Structure'),
        ),
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semester', verbose_name='Choose Academic Semester'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student', verbose_name='Choose Student'),
        ),
        migrations.AddField(
            model_name='paymentstructure',
            name='payment_description',
            field=models.ForeignKey(default='', help_text='payment for?', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.paymenttype', verbose_name='Payment Type'),
        ),
    ]
