# Generated by Django 4.1.1 on 2023-01-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_payment_paymenttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='payment_category_name',
            new_name='payment_type_name',
        ),
    ]
