# Generated by Django 4.1.1 on 2023-01-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_rename_payment_category_name_paymenttype_payment_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Total Amount To Be Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentstructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.paymentstructure', verbose_name='Payment Structure'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='semester',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semester', verbose_name='Academic Semester'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student', verbose_name='Student'),
        ),
    ]
