# Generated by Django 4.1.1 on 2023-01-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_remove_payment_total_payment_total_amount_to_be_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student', verbose_name='Student Name'),
        ),
    ]
